version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: run-dev
    environment:
      - PROJECT_NAME=Ultimate-bot-api
      - MONGODB_URL=mongodb://xxxxx:xxxxxx@192.168.1.1:27017
    ports:
      - 8080:80


  telegram-bot:
    build:
      context: ./
      dockerfile: ./bot/docker-compose/Dockerfile
    # command: run-telegram-bot
    # volumes:
    #   - ./app:/app
    environment:
      - "BOT_TOKEN=xxxxxxxxxxxxxxxxx"
      - BOT_NAME=comedores-ugr-api
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    user: 1000:1000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/alsa:/etc/alsa
      - "/usr/share/alsa:/usr/share/alsa"
      - "~/.config/pulse:/.config/pulse"
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - /dev/snd